import { Application, ApplicationStatus, Priority, WorkMode } from '@/types'
import { subDays, format } from 'date-fns'

function d(daysAgo: number): string {
  return format(subDays(new Date(), daysAgo), 'yyyy-MM-dd')
}

function iso(daysAgo: number): string {
  return subDays(new Date(), daysAgo).toISOString()
}

export const SEED_APPLICATIONS: Application[] = [
  {
    id: 'seed-1',
    company: 'Stripe',
    role: 'Senior Frontend Engineer',
    url: 'https://stripe.com/jobs',
    status: ApplicationStatus.INTERVIEW,
    priority: Priority.HIGH,
    workMode: WorkMode.HYBRID,
    location: 'San Francisco, CA',
    salaryMin: 180000,
    salaryMax: 230000,
    currency: 'USD',
    appliedAt: d(14),
    followUpDate: d(2),
    source: 'LinkedIn',
    nextAction: 'Prepare system design answers',
    contacts: [
      {
        id: 'c1',
        name: 'Sarah Chen',
        title: 'Engineering Manager',
        email: 'sarah.chen@stripe.com',
        linkedin: 'linkedin.com/in/sarahchen',
      },
    ],
    notes: [
      {
        id: 'n1',
        content: 'Had a great phone screen with Sarah. She mentioned the team is working on the payments infra revamp. Focus on React performance and TypeScript in the technical round.',
        createdAt: iso(10),
        updatedAt: iso(10),
      },
    ],
    statusHistory: [
      { id: 'sh1', status: ApplicationStatus.APPLIED, changedAt: iso(14) },
      { id: 'sh2', status: ApplicationStatus.PHONE_SCREEN, changedAt: iso(10) },
      { id: 'sh3', status: ApplicationStatus.INTERVIEW, changedAt: iso(5) },
    ],
    createdAt: iso(14),
    updatedAt: iso(5),
  },
  {
    id: 'seed-2',
    company: 'Vercel',
    role: 'Staff Software Engineer',
    url: 'https://vercel.com/careers',
    status: ApplicationStatus.APPLIED,
    priority: Priority.HIGH,
    workMode: WorkMode.REMOTE,
    location: 'Remote',
    salaryMin: 200000,
    salaryMax: 260000,
    currency: 'USD',
    appliedAt: d(8),
    followUpDate: d(1),
    source: 'Company Website',
    nextAction: 'Send follow-up email',
    contacts: [],
    notes: [
      {
        id: 'n2',
        content: 'Applied through careers page. Love their product. Would be a dream job. Tailored resume to emphasize Next.js and edge computing experience.',
        createdAt: iso(8),
        updatedAt: iso(8),
      },
    ],
    statusHistory: [
      { id: 'sh4', status: ApplicationStatus.APPLIED, changedAt: iso(8) },
    ],
    createdAt: iso(8),
    updatedAt: iso(8),
  },
  {
    id: 'seed-3',
    company: 'Linear',
    role: 'Frontend Engineer',
    url: 'https://linear.app/careers',
    status: ApplicationStatus.OFFER,
    priority: Priority.HIGH,
    workMode: WorkMode.REMOTE,
    location: 'Remote',
    salaryMin: 160000,
    salaryMax: 190000,
    currency: 'USD',
    appliedAt: d(30),
    followUpDate: d(0),
    source: 'Referral',
    nextAction: 'Respond to offer by Friday',
    contacts: [
      {
        id: 'c2',
        name: 'Alex Kim',
        title: 'Head of Engineering',
        email: 'alex@linear.app',
      },
    ],
    notes: [
      {
        id: 'n3',
        content: 'Received offer! Base $175k + equity. Need to compare with other offers. Deadline is this Friday.',
        createdAt: iso(2),
        updatedAt: iso(2),
      },
    ],
    statusHistory: [
      { id: 'sh5', status: ApplicationStatus.APPLIED, changedAt: iso(30) },
      { id: 'sh6', status: ApplicationStatus.PHONE_SCREEN, changedAt: iso(22) },
      { id: 'sh7', status: ApplicationStatus.INTERVIEW, changedAt: iso(15) },
      { id: 'sh8', status: ApplicationStatus.OFFER, changedAt: iso(2) },
    ],
    createdAt: iso(30),
    updatedAt: iso(2),
  },
  {
    id: 'seed-4',
    company: 'Notion',
    role: 'Software Engineer, Platform',
    url: 'https://notion.so/careers',
    status: ApplicationStatus.PHONE_SCREEN,
    priority: Priority.MEDIUM,
    workMode: WorkMode.HYBRID,
    location: 'New York, NY',
    salaryMin: 150000,
    salaryMax: 195000,
    currency: 'USD',
    appliedAt: d(18),
    followUpDate: d(3),
    source: 'LinkedIn',
    nextAction: 'Prepare for technical phone screen',
    contacts: [],
    notes: [],
    statusHistory: [
      { id: 'sh9', status: ApplicationStatus.APPLIED, changedAt: iso(18) },
      { id: 'sh10', status: ApplicationStatus.PHONE_SCREEN, changedAt: iso(6) },
    ],
    createdAt: iso(18),
    updatedAt: iso(6),
  },
  {
    id: 'seed-5',
    company: 'Figma',
    role: 'Senior Software Engineer',
    url: 'https://figma.com/careers',
    status: ApplicationStatus.REJECTED,
    priority: Priority.HIGH,
    workMode: WorkMode.HYBRID,
    location: 'San Francisco, CA',
    salaryMin: 190000,
    salaryMax: 240000,
    currency: 'USD',
    appliedAt: d(45),
    source: 'LinkedIn',
    contacts: [],
    notes: [
      {
        id: 'n4',
        content: 'Got rejected after final round. Feedback: needed stronger system design skills. Will practice more before next application.',
        createdAt: iso(7),
        updatedAt: iso(7),
      },
    ],
    statusHistory: [
      { id: 'sh11', status: ApplicationStatus.APPLIED, changedAt: iso(45) },
      { id: 'sh12', status: ApplicationStatus.PHONE_SCREEN, changedAt: iso(38) },
      { id: 'sh13', status: ApplicationStatus.INTERVIEW, changedAt: iso(28) },
      { id: 'sh14', status: ApplicationStatus.REJECTED, changedAt: iso(7) },
    ],
    createdAt: iso(45),
    updatedAt: iso(7),
  },
  {
    id: 'seed-6',
    company: 'Loom',
    role: 'React Engineer',
    url: 'https://loom.com/careers',
    status: ApplicationStatus.WISHLIST,
    priority: Priority.MEDIUM,
    workMode: WorkMode.REMOTE,
    location: 'Remote',
    currency: 'USD',
    appliedAt: d(0),
    source: 'Job Board',
    contacts: [],
    notes: [],
    statusHistory: [],
    createdAt: iso(3),
    updatedAt: iso(3),
  },
  {
    id: 'seed-7',
    company: 'Retool',
    role: 'Full Stack Engineer',
    url: 'https://retool.com/careers',
    status: ApplicationStatus.APPLIED,
    priority: Priority.MEDIUM,
    workMode: WorkMode.HYBRID,
    location: 'San Francisco, CA',
    salaryMin: 160000,
    salaryMax: 200000,
    currency: 'USD',
    appliedAt: d(5),
    source: 'Referral',
    contacts: [],
    notes: [],
    statusHistory: [
      { id: 'sh15', status: ApplicationStatus.APPLIED, changedAt: iso(5) },
    ],
    createdAt: iso(5),
    updatedAt: iso(5),
  },
  {
    id: 'seed-8',
    company: 'Planetscale',
    role: 'Developer Experience Engineer',
    url: 'https://planetscale.com/careers',
    status: ApplicationStatus.GHOSTED,
    priority: Priority.LOW,
    workMode: WorkMode.REMOTE,
    location: 'Remote',
    currency: 'USD',
    appliedAt: d(60),
    source: 'Twitter',
    contacts: [],
    notes: [
      {
        id: 'n5',
        content: 'Applied 2 months ago, never heard back. Marking as ghosted.',
        createdAt: iso(5),
        updatedAt: iso(5),
      },
    ],
    statusHistory: [
      { id: 'sh16', status: ApplicationStatus.APPLIED, changedAt: iso(60) },
      { id: 'sh17', status: ApplicationStatus.GHOSTED, changedAt: iso(5) },
    ],
    createdAt: iso(60),
    updatedAt: iso(5),
  },
]
